# Generated by Django 5.2.1 on 2025-05-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
    ]
