# Generated by Django 5.2.1 on 2025-05-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donation_transaction_id'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
